package net.milosvasic.factory.configuration

import net.milosvasic.factory.common.initialization.InitializationOperation

class ConfigurationManagerInitializationOperation : InitializationOperation()